"""Flat info.toml manifest for the curriculum.

One [[day]] array entry per day. Single source of truth for the day
list, replaces walking the phase/module/day folder tree.
"""
from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class DayEntry:
    slug: str
    path: str
    day_number: int
    phase: str
    module: str
    old_slug: str
    patterns: list[str] = field(default_factory=list)


def load(path: Path) -> list[DayEntry]:
    """Read info.toml. Returns [] if the file doesn't exist."""
    if not path.is_file():
        return []
    data = tomllib.loads(path.read_text())
    return [
        DayEntry(
            slug=d["slug"],
            path=d["path"],
            day_number=d["day_number"],
            phase=d["phase"],
            module=d["module"],
            old_slug=d["old_slug"],
            patterns=list(d.get("patterns", [])),
        )
        for d in data.get("day", [])
    ]


def dump(entries: list[DayEntry], path: Path) -> None:
    """Write info.toml. Hand-rolled (no tomli_w dependency).

    The schema avoids strings that need TOML escaping (slugs match
    [a-z0-9-]+). If that ever changes, swap in tomli_w.
    """
    lines: list[str] = [
        "# Auto-generated by scripts/migrate_v1_to_v2.py.\n",
        "# Do not edit by hand — regenerate via the migration script.\n",
    ]
    for e in entries:
        patterns = ", ".join(f'"{p}"' for p in e.patterns)
        lines.append("\n[[day]]\n")
        lines.append(f'slug = "{e.slug}"\n')
        lines.append(f'path = "{e.path}"\n')
        lines.append(f'day_number = {e.day_number}\n')
        lines.append(f'phase = "{e.phase}"\n')
        lines.append(f'module = "{e.module}"\n')
        lines.append(f'old_slug = "{e.old_slug}"\n')
        lines.append(f'patterns = [{patterns}]\n')
    path.write_text("".join(lines))
