"""Flat info.toml manifest for the curriculum.

One [[day]] array entry per day. Single source of truth for the day
list, replaces walking the phase/module/day folder tree.
"""
from __future__ import annotations

import json
import tomllib
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class DayEntry:
    slug: str
    path: str
    day_number: int
    phase: str
    module: str
    old_slug: str
    patterns: list[str] = field(default_factory=list)


def load(path: Path) -> list[DayEntry]:
    """Read info.toml. Returns [] if the file doesn't exist."""
    if not path.is_file():
        return []
    data = tomllib.loads(path.read_text())
    return [
        DayEntry(
            slug=d["slug"],
            path=d["path"],
            day_number=d["day_number"],
            phase=d["phase"],
            module=d["module"],
            old_slug=d["old_slug"],
            patterns=list(d.get("patterns", [])),
        )
        for d in data.get("day", [])
    ]


def dump(entries: list[DayEntry], path: Path) -> None:
    """Write info.toml. Hand-rolled (no tomli_w dependency).

    String fields are quoted via ``json.dumps`` — TOML basic-string
    escaping is a superset of JSON's, so any value that round-trips
    through JSON also round-trips through TOML. That makes the writer
    safe for slugs, phase/module names, paths, and pattern names that
    contain quotes, backslashes, newlines, or non-ASCII chars without
    needing a third-party `tomli_w` dependency.
    """
    lines: list[str] = [
        "# Auto-generated by scripts/migrate_v1_to_v2.py.\n",
        "# Do not edit by hand — regenerate via the migration script.\n",
    ]
    q = json.dumps  # alias: produces TOML-valid basic-string quoting
    for e in entries:
        patterns = ", ".join(q(p) for p in e.patterns)
        lines.append("\n[[day]]\n")
        lines.append(f'slug = {q(e.slug)}\n')
        lines.append(f'path = {q(e.path)}\n')
        lines.append(f'day_number = {e.day_number}\n')
        lines.append(f'phase = {q(e.phase)}\n')
        lines.append(f'module = {q(e.module)}\n')
        lines.append(f'old_slug = {q(e.old_slug)}\n')
        lines.append(f'patterns = [{patterns}]\n')
    path.write_text("".join(lines))


def regenerate_from_skeleton(
    curriculum: Path,
    skeleton: list[tuple[str, str, list[str]]],
    old_slug_fn: Callable[[str], str],
) -> None:
    """Rewrite curriculum/info.toml from a SKELETON, preserving patterns.

    Used by the M6 / M11 / future restructure scripts. `old_slug_fn`
    maps a new slug to the v1 slug a learner's progress.json may
    still carry, so locator.find_day's back-compat keeps resolving.
    """
    existing = {e.slug: e for e in load(curriculum / "info.toml")}
    entries: list[DayEntry] = []
    for phase, module, day_slugs in skeleton:
        for slug in day_slugs:
            day_number = int(slug.split("-")[0])
            patterns = existing[slug].patterns if slug in existing else []
            entries.append(DayEntry(
                slug=slug,
                path=f"curriculum/{slug}",
                day_number=day_number,
                phase=phase,
                module=module,
                old_slug=old_slug_fn(slug),
                patterns=patterns,
            ))
    dump(entries, curriculum / "info.toml")
